-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 21:40:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tienda` ;

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda` DEFAULT CHARACTER SET utf8 ;
USE `tienda` ;

-- -----------------------------------------------------
-- Table `tienda`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`rol` (
  `idRol` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`usuario` (
  `email` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `paterno` VARCHAR(45) NOT NULL,
  `materno` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `idRol` INT(11) NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `idRol`
    FOREIGN KEY (`idRol`)
    REFERENCES `tienda`.`rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idRol_idx` ON `tienda`.`usuario` (`idRol` ASC);


-- -----------------------------------------------------
-- Table `tienda`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`admin` (
  `idAdmin` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  CONSTRAINT `email`
    FOREIGN KEY (`email`)
    REFERENCES `tienda`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `email_idx` ON `tienda`.`admin` (`email` ASC);


-- -----------------------------------------------------
-- Table `tienda`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `monedero` DOUBLE NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `email_fk`
    FOREIGN KEY (`email`)
    REFERENCES `tienda`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `email_idx` ON `tienda`.`cliente` (`email` ASC);


-- -----------------------------------------------------
-- Table `tienda`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`compra` (
  `idCompra` INT(11) NOT NULL AUTO_INCREMENT,
  `idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`idCompra`),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `tienda`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idCliente_idx` ON `tienda`.`compra` (`idCliente` ASC);


-- -----------------------------------------------------
-- Table `tienda`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`categoria` (
  `idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`producto` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `stock` INT(11) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `descuento` DOUBLE NOT NULL,
  `idCategoria` INT(11) NOT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `tienda`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idCategoria_idx` ON `tienda`.`producto` (`idCategoria` ASC);


-- -----------------------------------------------------
-- Table `tienda`.`carrito_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`carrito_compra` (
  `idProducto` INT(11) NOT NULL,
  `idCompra` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  CONSTRAINT `idCompra`
    FOREIGN KEY (`idCompra`)
    REFERENCES `tienda`.`compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `tienda`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idProducto_idx` ON `tienda`.`carrito_compra` (`idProducto` ASC);

CREATE INDEX `idCompra_idx` ON `tienda`.`carrito_compra` (`idCompra` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;